INSERT INTO `categories` (`id`, `category`) VALUES (1, 'Music'),
(2, 'Fashion'),
(3, 'Car'),
(4, 'Real Estate'),
(5, 'Beauty'),
(6, 'Travel'),
(7, 'Design'),
(8, 'Food'),
(9, 'Wedding'),
(10, 'Movie'),
(11, 'Photography'),
(12, 'Law'),
(13, 'Health'),
(14, 'Green'),
(15, 'Technology'),
(16, 'SEO'),
(17, 'History'),
(18, 'Marketing'),
(19, 'Lifestyle'),
(20, 'University'),
(21, 'Dog'),
(22, 'Money'),
(23, 'Business'),
(24, 'Fitness'),
(25, 'Education'),
(26, 'Science'),
(27, 'Shopping'),
(28, 'Entertainment'),
(29, 'Sports'),
(30, 'Cat'),
(31, 'Social Media'),
(32, 'Medical'),
(33, 'Wine'),
(34, 'Celebrity Gossip'),
(35, 'DIY'),
(36, 'Nature'),
(37, 'Gaming'),
(38, 'Pet'),
(39, 'Finance'),
(40, 'Political'),
(41, 'Career'),
(42, 'Parenting'),
(43, 'Economics');